---
title: "U Up? Sleep and GPA of First-Year College Students"
output: 
  html_document:
    toc: true
    toc_float: true
---

Group Members: Kate Colvin (kac2301), Yuying Lu (yl5839), and Chhiring Lama (cyl2159)

--- 

## Motivation

Student lack of success and under-performance in college is a large waste of human capital and money. It is widely known that student academic success depends on a number of factors, including regular sleep habits. Our goal in this study is to better understand how first-year GPA is impacted by sleeping behavior, while controlling for multiple demographic factors across three distinct universities. Additionally, understanding how demographic factors are related to sleeping behavior can provide guidance to universities on how to allocate resources to student behavioral health initiatives to best improve student success. 

Finally, as previous undergraduates, current graduate students, and potentially future educators, understanding how sleeping behavior impacts academic performance is a personally compelling topic. 

## Related work

The data for our project came from a 2023 study, ["Nightly sleep duration predicts grade point average in the first year of college" ](https://www.pnas.org/doi/10.1073/pnas.2209123120), by JD Creswell et al. In this study, they found that term GPA and total sleep time were positively associated. Their multiple regression analysis controlled for daytime sleep, demographic variables, and standardized course load. All previous studies on this topic relied on self-reported recollections of total sleep time, which is prone to recall bias, and excludes other potentially important measures of sleep behavior. 

Our project aimed to expand upon the study conducted by JD Creswell et al in several ways: to further explore the distributions of and correlations between the demographic, academic, and sleep behavior variables they collected; improve upon the models they used to predict GPA; and to create an interactive Shiny app to predict GPA based on users-inputted demographic factors and sleep behavior. 

## Initial questions

Initially, our proposed project was to study how the lifestyle habits of college students impacted their duration and quality of sleep. As we researched further into this topic, we found a greater amount of real-world data available covering sleeping behavior and academic performance, which pushed us to instead look at sleeping behavior as a predictor of GPA. 

Our primary questions heading into this project were: 

* How are course load and GPA distributed in different gender, race, educational background and colleges?
* What are the main sleeping patterns seen in students over multiple measures of sleeping behavior? 
* What can we learn about the relationship between academic performance, demographic characteristics, and sleeping habits in first-year college students? Can academic performance be predicted using these variables?

As we explored the data further, several additional questions came up regarding the variables relationships with each other and how the structure of the study may impact our results: 

* How is course load related to GPA overall, and in various demographic sub-groups?
* How are different sleeping behaviors related to each other? How will this inform our regression models? 
* How important are the characteristic differences of the three universities recruited in this study (Carnegie Mellon, Notre Dame, and University of Washington)? Will this change what demographic and sleeping variables are most predictive of GPA?

## Data
Source, scraping method, cleaning, etc.

## Exploratory analysis
Visualizations, summaries, and exploratory statistical analyses. Justify the steps you took, and show any major changes to your ideas.

Our exploratory analysis is broken into two main sections: [student data](students.html) and [sleeping behavior](sleep_metrics.html). 


## Additional analysis
If you undertake formal statistical analyses, describe these in detail

## Discussion 
What were your findings? Are they what you expect? What insights into the data can you make?

